Repository Mine4Cut/Mine4Cut-server, pull requests merged in 2025-07, with the labels that each got.

#2 Feat: add common-response-dto
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/dto/ApiResponse.java
  src/test/java/io/github/Mine4Cut/Mine4Cut_server/Mine4CutServerApplicationTests.java
Labels: size/M

#4 Feat: User Entity 생성 및 jwt 토큰 인증 방식 추가
  README.md
  build.gradle
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/user/UserDto.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/authentication/jwt/JwtAuthenticationFilter.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/authentication/jwt/JwtTokenProvider.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/authentication/security/config/SecurityConfiguration.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/dto/ApiResponse.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/dto/PageResponse.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/user/User.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/user/UserRepository.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/ErrorCode.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/io/github/Mine4Cut/Mine4Cut_server/exception/GlobalExceptionHandlerTest.java
Labels: size/L

#5 Test: Jwt Token 생성, 검증, 인증, 만료 테스트
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/authentication/jwt/JwtAuthenticationFilter.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/authentication/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/io/github/Mine4Cut/Mine4Cut_server/JwtTokenTest/JwtTokenProviderTest.java
Labels: size/L

#6 [Feat/base entity] - BaseEntity 생성
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/entity/BaseEntity.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/config/JpaAuditConfig.java
Labels: size/M, :rocket: feature :rocket:

#8 [Refactor/user authentication]
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/Mine4CutServerApplication.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/auth/JwtAuthenticationFilter.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/auth/SignInController.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/auth/dto/AuthResponse.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/config/SecurityConfiguration.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/config/UserArgumentResolver.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/config/UserContextHolder.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/config/WebConfig.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/user/controller/SignUpController.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/user/dto/SignInRequest.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/api/user/dto/SignUpRequest.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/dto/ApiResponse.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/dto/PageResponse.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/common/entity/BaseEntity.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/config/JpaAuditConfig.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/config/JwtConfig.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/config/JwtProperties.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/user/dto/UserDto.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/user/entity/Role.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/user/entity/User.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/domain/user/repository/UserRepository.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/AuthorizationException.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/CustomException.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/ErrorResponse.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/GlobalExceptionHandler.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/exception/NotFoundException.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/security/jwt/JwtAuthenticationFilter.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/security/jwt/JwtTokenProvider.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/AuthService.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/CustomUserDetailsService.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/JwtTokenProvider.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/JwtUserService.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/dto/CustomUserDetails.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/dto/JwtUserInfo.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/auth/dto/ParsedJwtInfo.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/user/UserService.java
  src/main/java/io/github/Mine4Cut/Mine4Cut_server/service/user/dto/SignInDto.java
  src/test/java/io/github/Mine4Cut/Mine4Cut_server/JwtTokenTest/JwtTokenProviderTest.java
  src/test/java/io/github/Mine4Cut/Mine4Cut_server/api/config/UserArgumentResolverTest.java
  src/test/java/io/github/Mine4Cut/Mine4Cut_server/exception/GlobalExceptionHandlerTest.java
Labels: size/XXL
